
name: dakhila_camera
description: Camera app that saves image by DAKHILA value
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  path: ^1.8.3
  provider: ^6.1.1
  image: ^4.1.7
  cupertino_icons: ^1.0.6
  file_picker: ^12.3.0
  android_intent_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/Data_basic.json
