org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
# Windows-এ Kotlin incremental cache lock error (android_file_picker build fail) এড়াতে
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
